name: Main Branch CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Check Formatting
        run: npm run format:check

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Tag Release
        id: tagger
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const packageJson = require('./package.json');
            const version = packageJson.version;
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
            const tagName = `v${version}`;
            const releaseName = `Release ${tagName}`;
            console.log(`Creating release ${releaseName}`);
            const response = await github.repos.createRelease({
              owner,
              repo,
              tag_name: tagName,
              name: releaseName,
              body: `Changes in this Release:\n- Your changelog here`,
              draft: false,
              prerelease: false
            });
            return response.data.tag_name;

      - name: Install AWS CLI
        run: sudo apt-get install awscli

      - name: Configure AWS Default Region
        run: aws configure set default.region eu-west-3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Development S3
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: |
          aws s3 sync ./build s3://checkflow.fr --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
